<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Oxigraph\Oxigraph.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dotNetRdf" Version="3.5.2" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>Oxigraph.Extensions.DotNetRDF</RootNamespace>
    <AssemblyName>Oxigraph.Extensions.DotNetRDF</AssemblyName>
    <PackageId>Oxigraph.Extensions.DotNetRDF</PackageId>
    <Description>dotNetRDF interoperability adapters for Oxigraph</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>